### ISSUE TITLE
Time-Switch Widget wird auf meinem Tablet Android 8.1 nicht angezeigt

### ISSUE THREAD

**Issue by Harry2009** [walli545/ioBroker.time-switch#122]
Time and Switch Widget wird auf meinem Tablet Android 8.1 nicht angezeigt. Mein View bleibt Leer. Über Firefox ist das Widget in meinem Vis-Projekt Sichtbar.Hat jemand eine Idee?
Time-Switch Version 2.1. Also die Aktuelle

**Comment by Harry2009** [comment]
Hatte vergessen zu schreiben das auf meinem Tablet die IObroker Vis App läuft.

**Comment by walli545** [comment]
Hi, aktuell funktioniert das Widget nicht mit der Vis App, dafür muss der Adapter erst offiziell veröffentlicht werden und in die App mit Aufgenommen werden. Dafür gibt es bereits einen anderen Issue #32. Daher werde ich diesen hier schließen.
