### ISSUE TITLE
Astro trigger are not working proper

### ISSUE THREAD

**Issue by BigDi** [walli545/ioBroker.time-switch#123]
I used the astro trigger (sun set/sun dawn) on several switch points. Sometimes is works, sometimes not. I also switched on logging to debug. But no usable output. Any suggestions?

**Comment by walli545** [comment]
I think I found the error and fixed it with **2.2.0-pre.5**. You can install it from https://github.com/walli545/ioBroker.time-switch/tarball/dev.
Please try it out, especially if it works consistently over multiple days as I think before it worked only on the first day when setting up the triggers and not on any of the following days. If the issue still persists, please reopen this issue.
