### ISSUE TITLE
Improvement data-object

### ISSUE THREAD

**Issue by SVallant** [walli545/ioBroker.time-switch#27]
Since you have the same actions and states for all triggers, i suggest to change the schedule-object to:
`{
  "name": "New Schedule",
  "action": {
    "type": "OnOffStateAction",
    "valueType": "boolean",
    "onValue": true,
    "offValue": false,
    "booleanValue": true,
    "idsOfStatesToSet": [
      "0_userdata.0.demodata.switch",
      "0_userdata.0.demodata.indicator"
    ]
  },
  "triggers": [
    {
      "type": "TimeTrigger",
      "hour": 0,
      "minute": 0,
      "weekdays": [
        1,
        2,
        3,
        4,
        5,
        6,
        0
      ],
      "id": "0",
      "value": "onORoffValue"
    }
  ]
}`

**Comment by walli545** [comment]
This is the new data structure:
```
{ 
   "type": "OnOffSchedule",
   "name": "My Schedule 2",
   "onAction": { 
      "type": "OnOffStateAction",
      "valueType": "number",
      "onValue": 1, 
      "offValue": 0,
      "booleanValue": true,
      "idsOfStatesToSet": ["0_userdata.0.number1","0_userdata.0.bool1"]
    },
  "offAction": { 
     "type": "OnOffStateAction",
    "valueType": "number",
    "onValue": 1,
    "offValue": 0,
    "booleanValue": false,
    "idsOfStatesToSet" :["0_userdata.0.number1","0_userdata.0.bool1"]
  },
  "triggers": [
    {
       "type":"TimeTrigger",
       "hour":13,
       "minute":41,
       "weekdays":[1,2,3,4,5,6,0],
       "id":"1",
       "action": {
          "type":"OnOffStateAction",
          "name":"Off"
        }
   },
  {
       "type":"TimeTrigger",
       "hour":13,
       "minute":41,
       "weekdays":[1,2,3,4,5,6,0],
       "id":"1",
       "action": {
          "type":"OnOffStateAction",
          "name":"On"
        }
   }
   ]
}
```


There is now an onAction and an offAction in the schedule object. In the TimeTrigger there is only a reference to either the on or the off action via
 ```
{
  "type":"OnOffStateAction",
   "name":"On" | "Off"
}
```
